version: '3.8'

services:
  app:
    build: .
    image: library-management-api
    container_name: library-container
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    volumes:
      - .:/app
    networks:
      - flask-network

networks:
  flask-network:
    driver: bridge
